yarnPath: .yarn/releases/yarn-4.10.3.cjs

# Enable zero-installs (optional - stores packages in .yarn/cache)
# enableGlobalCache: false

# Set the node linker to 'node-modules' for compatibility with existing tools
nodeLinker: node-modules

# Package manager configuration
enableTelemetry: false

# Workspace configuration
enableTransparentWorkspaces: false
