yarnPath: .yarn/releases/yarn-4.10.3.cjs

# Enable zero-installs (optional - stores packages in .yarn/cache)
# enableGlobalCache: false

# Set the node linker to 'node-modules' for compatibility with existing tools
nodeLinker: node-modules

# Package manager configuration
enableTelemetry: false

# Workspace configuration
enableTransparentWorkspaces: false

plugins:
  - checksum: 44a06a583a46ab1e2de2a04c115868bea51f01a314f261b628fbf6d92b2be63c0d155be3d3094d440daf58ff3f263aba4c9384a1c60c5d26cc0db086ad990459
    path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: 'https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.7.0/bundles/@yarnpkg/plugin-after-install.js'

afterInstall: node add-react-debug-info.js